name: Hub - Test
on:
  push:
    paths:
      - ".github/workflows/hub-test.yml"
      - "packages/hub/**"
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/hub-test.yml"
      - "packages/hub/**"

defaults:
  run:
    working-directory: packages/hub

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.1.5
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "packages/hub/pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
